"""add projects and ticket relationship

Revision ID: 209bac1ec56c
Revises: ed8b7e21ff0b
Create Date: 2026-09-22 18:47:28.191146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '209bac1ec56c'
down_revision: Union[str, Sequence[str], None] = 'ed8b7e21ff0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tickets', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key( "fk_tickets_project_id_projects", 'tickets', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint("fk_tickets_project_id_projects", 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'project_id')
    op.drop_table('projects')
    # ### end Alembic commands ###
