"""add ticket status

Revision ID: 9bd3e0debda4
Revises: 4d621157cb72
Create Date: 2026-10-02 12:52:55.019854

"""
from typing import Sequence, Union
from sqlalchemy.dialects import postgresql
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bd3e0debda4'
down_revision: Union[str, Sequence[str], None] = '4d621157cb72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
ticket_status_enum = postgresql.ENUM(
    "OPEN",
    "IN_PROGRESS",
    "DONE",
    name="ticketstatus"
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    ticket_status_enum.create(
        op.get_bind(),
        checkfirst=True
    )
    op.add_column('tickets', sa.Column('status', ticket_status_enum, nullable=True))
    op.execute("UPDATE tickets SET status = 'OPEN' WHERE status IS NULL")
    op.alter_column("tickets", "status", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'status')
    ticket_status_enum.drop(
        op.get_bind(),
        checkfirst=True
    )
    # ### end Alembic commands ###
