"""add ticket priority check

Revision ID: bb3d3d602433
Revises: f940114c8739
Create Date: 2026-10-04 12:59:53.915395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb3d3d602433'
down_revision: Union[str, Sequence[str], None] = 'f940114c8739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "priority_check",
        "tickets",
        "priority >= 1 AND priority <= 5"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "priority_check",
        "tickets",
        type_="check"
    )
    # ### end Alembic commands ###
