"""add ticket project priority index

Revision ID: f940114c8739
Revises: 4a4de01542f6
Create Date: 2026-10-04 12:50:36.043042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f940114c8739'
down_revision: Union[str, Sequence[str], None] = '4a4de01542f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tickets_project_id_priority', 'tickets', ['project_id', 'priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tickets_project_id_priority', table_name='tickets')
    # ### end Alembic commands ###
